disabled_rules:
  - block_based_kvo
  - variable_name
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - type_body_length
  - function_parameter_count
  - discarded_notification_center_observer
  - line_length
  - large_tuple
